WARNING 2023-10-21 14:29:15,944 django.request Thread-6 (process_request_thread) 16468 log log.py 241 django.request log_response 33212 Not Found: /favicon.ico
WARNING 2023-10-21 14:29:15,947 django.server Thread-6 (process_request_thread) 16468 basehttp basehttp.py 212 django.server log_message 33212 "GET /favicon.ico HTTP/1.1" 404 17824
WARNING 2023-10-22 05:41:25,703 django.request Thread-1 (process_request_thread) 20468 log log.py 241 django.request log_response 21912 Not Found: /favicon.ico
WARNING 2023-10-22 05:41:25,706 django.server Thread-1 (process_request_thread) 20468 basehttp basehttp.py 212 django.server log_message 21912 "GET /favicon.ico HTTP/1.1" 404 17824
ERROR 2023-10-22 05:44:51,369 django.request Thread-1 (process_request_thread) 20468 log log.py 241 django.request log_response 21912 Internal Server Error: /sign_in/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\utilities\decorators.py", line 11, in wrapper_func
    return view_func(request,*args,**kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\website\views.py", line 130, in sign_in
    group = Group.objects.get(name='student')
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
ERROR 2023-10-22 05:44:51,467 django.server Thread-1 (process_request_thread) 20468 basehttp basehttp.py 212 django.server log_message 21912 "POST /sign_in/ HTTP/1.1" 500 94693
WARNING 2023-10-22 05:46:12,204 django.request Thread-1 (process_request_thread) 20468 log log.py 241 django.request log_response 21912 Not Found: /Specialization
WARNING 2023-10-22 05:46:12,206 django.server Thread-1 (process_request_thread) 20468 basehttp basehttp.py 212 django.server log_message 21912 "GET /Specialization HTTP/1.1" 404 17836
WARNING 2023-10-22 05:46:16,060 django.request Thread-1 (process_request_thread) 20468 log log.py 241 django.request log_response 21912 Not Found: /Jobs
WARNING 2023-10-22 05:46:16,061 django.server Thread-1 (process_request_thread) 20468 basehttp basehttp.py 212 django.server log_message 21912 "GET /Jobs HTTP/1.1" 404 17795
WARNING 2023-10-22 05:57:39,828 django.server Thread-1 (process_request_thread) 20468 basehttp basehttp.py 212 django.server log_message 21912 "GET /static/css/job_pos.css HTTP/1.1" 404 1804
WARNING 2023-10-22 06:04:44,207 django.request Thread-7 (process_request_thread) 1732 log log.py 241 django.request log_response 10916 Not Found: /favicon.ico
WARNING 2023-10-22 06:04:44,214 django.server Thread-7 (process_request_thread) 1732 basehttp basehttp.py 212 django.server log_message 10916 "GET /favicon.ico HTTP/1.1" 404 17823
WARNING 2023-10-22 06:32:35,727 django.server Thread-9 (process_request_thread) 14280 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:33:03,301 django.server Thread-10 (process_request_thread) 21012 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:34:40,118 django.server Thread-11 (process_request_thread) 12828 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:34:41,228 django.server Thread-12 (process_request_thread) 29692 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:35:14,662 django.server Thread-13 (process_request_thread) 9612 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:35:15,663 django.server Thread-14 (process_request_thread) 30960 basehttp basehttp.py 212 django.server log_message 10916 "GET /static/css/1.png HTTP/1.1" 404 1786
WARNING 2023-10-22 06:36:39,838 django.server Thread-1 (process_request_thread) 10112 basehttp basehttp.py 212 django.server log_message 28848 "GET /static/css/images/1.png HTTP/1.1" 404 1807
WARNING 2023-10-22 06:37:33,772 django.request Thread-2 (process_request_thread) 9812 log log.py 241 django.request log_response 28848 Not Found: /images/1.png
WARNING 2023-10-22 06:37:33,773 django.server Thread-2 (process_request_thread) 9812 basehttp basehttp.py 212 django.server log_message 28848 "GET /images/1.png HTTP/1.1" 404 17827
WARNING 2023-10-22 06:38:32,943 django.request Thread-2 (process_request_thread) 9812 log log.py 241 django.request log_response 28848 Not Found: /course-u/static/images/1.png
WARNING 2023-10-22 06:38:32,944 django.server Thread-2 (process_request_thread) 9812 basehttp basehttp.py 212 django.server log_message 28848 "GET /course-u/static/images/1.png HTTP/1.1" 404 17891
WARNING 2023-10-22 06:38:34,202 django.request Thread-2 (process_request_thread) 9812 log log.py 241 django.request log_response 28848 Not Found: /course-u/static/images/1.png
WARNING 2023-10-22 06:38:34,205 django.server Thread-2 (process_request_thread) 9812 basehttp basehttp.py 212 django.server log_message 28848 "GET /course-u/static/images/1.png HTTP/1.1" 404 17891
WARNING 2023-10-25 10:53:54,042 django.request Thread-3 (process_request_thread) 25196 log log.py 241 django.request log_response 11828 Not Found: /favicon.ico
WARNING 2023-10-25 10:53:54,044 django.server Thread-3 (process_request_thread) 25196 basehttp basehttp.py 212 django.server log_message 11828 "GET /favicon.ico HTTP/1.1" 404 17824
WARNING 2023-10-25 11:30:46,224 django.request Thread-4 (process_request_thread) 28788 log log.py 241 django.request log_response 32224 Not Found: /favicon.ico
WARNING 2023-10-25 11:30:46,226 django.server Thread-4 (process_request_thread) 28788 basehttp basehttp.py 212 django.server log_message 32224 "GET /favicon.ico HTTP/1.1" 404 17823
ERROR 2023-10-25 11:50:35,558 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\website\views.py", line 168, in user_profile
    return render(request, 'user/user_profile.html', context)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-25 11:50:35,596 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /profile/ HTTP/1.1" 500 196969
ERROR 2023-10-25 11:50:37,088 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\website\views.py", line 168, in user_profile
    return render(request, 'user/user_profile.html', context)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-25 11:50:37,125 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /profile/ HTTP/1.1" 500 196969
ERROR 2023-10-25 11:51:32,690 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\website\views.py", line 168, in user_profile
    return render(request, 'user/user_profile.html', context)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-25 11:51:32,726 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /profile/ HTTP/1.1" 500 197118
ERROR 2023-10-25 11:51:33,182 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\website\views.py", line 168, in user_profile
    return render(request, 'user/user_profile.html', context)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-25 11:51:33,214 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /profile/ HTTP/1.1" 500 197117
ERROR 2023-10-25 12:00:21,339 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /course_input/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\assessment\views.py", line 385, in course_input
    return render(request,'user/course.html')
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
ERROR 2023-10-25 12:00:21,373 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /course_input/ HTTP/1.1" 500 147998
ERROR 2023-10-25 12:00:22,349 django.request Thread-2 (process_request_thread) 8356 log log.py 241 django.request log_response 27744 Internal Server Error: /course_input/
Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Cedrick Estolas\course-u\course-u\assessment\views.py", line 385, in course_input
    return render(request,'user/course.html')
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Cedrick Estolas\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
ERROR 2023-10-25 12:00:22,384 django.server Thread-2 (process_request_thread) 8356 basehttp basehttp.py 212 django.server log_message 27744 "GET /course_input/ HTTP/1.1" 500 147997
WARNING 2023-10-25 20:09:13,537 django.request Thread-1 (process_request_thread) 33352 log log.py 241 django.request log_response 32992 Not Found: /favicon.ico
WARNING 2023-10-25 20:09:13,539 django.server Thread-1 (process_request_thread) 33352 basehttp basehttp.py 212 django.server log_message 32992 "GET /favicon.ico HTTP/1.1" 404 17823
WARNING 2023-10-25 20:09:13,939 django.request Thread-2 (process_request_thread) 7080 log log.py 241 django.request log_response 32992 Not Found: /favicon.ico
WARNING 2023-10-25 20:09:13,941 django.server Thread-2 (process_request_thread) 7080 basehttp basehttp.py 212 django.server log_message 32992 "GET /favicon.ico HTTP/1.1" 404 17824
WARNING 2023-10-27 13:13:28,598 django.request Thread-2 (process_request_thread) 11568 log log.py 241 django.request log_response 19304 Not Found: /favicon.ico
WARNING 2023-10-27 13:13:28,601 django.server Thread-2 (process_request_thread) 11568 basehttp basehttp.py 212 django.server log_message 19304 "GET /favicon.ico HTTP/1.1" 404 17823
WARNING 2023-10-27 13:23:21,765 django.request Thread-16 (process_request_thread) 29840 log log.py 241 django.request log_response 19304 Not Found: /favicon.ico
WARNING 2023-10-27 13:23:21,768 django.server Thread-16 (process_request_thread) 29840 basehttp basehttp.py 212 django.server log_message 19304 "GET /favicon.ico HTTP/1.1" 404 17823
WARNING 2023-10-27 13:32:29,783 django.server Thread-1 (process_request_thread) 508 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:32:30,786 django.server Thread-2 (process_request_thread) 22048 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:32:48,893 django.server Thread-3 (process_request_thread) 19064 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:33:24,265 django.server Thread-4 (process_request_thread) 12748 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:33:32,734 django.server Thread-5 (process_request_thread) 26160 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:34:14,325 django.server Thread-6 (process_request_thread) 24184 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-10-27 13:34:15,325 django.server Thread-7 (process_request_thread) 24564 basehttp basehttp.py 212 django.server log_message 13144 "GET /static/css/logout_success.css HTTP/1.1" 404 1825
WARNING 2023-11-03 12:56:45,502 django.request Thread-3 (process_request_thread) 12976 log log.py 241 django.request log_response 15040 Not Found: /favicon.ico
WARNING 2023-11-03 12:56:45,503 django.server Thread-3 (process_request_thread) 12976 basehttp basehttp.py 212 django.server log_message 15040 "GET /favicon.ico HTTP/1.1" 404 17824
WARNING 2023-11-03 13:35:01,846 django.request Thread-2 (process_request_thread) 5876 log log.py 241 django.request log_response 13240 Not Found: /favicon.ico
WARNING 2023-11-03 13:35:01,849 django.server Thread-2 (process_request_thread) 5876 basehttp basehttp.py 212 django.server log_message 13240 "GET /favicon.ico HTTP/1.1" 404 17824
